### ISSUE TITLE
What is included in the do-k8s secrets 

### ISSUE THREAD

**Issue by hantsy** [semaphoreci-demos/semaphore-demo-ruby-kubernetes#13]
I have tried to add the k8s deployment flow to my sample, failed. 

https://hantsy.semaphoreci.com/jobs/3dccde86-887b-440d-bb8f-c7d1f932b459

I can not find any description in the document(microservice in ci/cd) about it.

**Comment by markoa** [comment]
Hi @hantsy, this is described in detail on https://semaphoreci.com/blog/cicd-microservices-digitalocean-kubernetes

**Comment by hantsy** [comment]
I got this repo from docs https://docs.semaphoreci.com/examples/ci-cd-for-microservices-on-kubernetes/
I think it is better to add a link to this blog entry or enrich this doc.
